### PR TITLE
fix the xmlbuilder bug

### PR DESCRIPTION
**Pull request by qiaozha**
resolve https://github.com/Azure/azure-sdk-for-node/issues/5181

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by qiaozha** [comment]
@ramya-rao-a  @joheredi  Can you help review this PR. Looks like the CI testing fail is because of the bug I am trying to fix.

**Comment by joheredi** [comment]
@qiaozha I'm not familiar with this package, can you please provide some details on what is the bug that this PR is fixing? I see that the error message is `Error: Cannot find module 'xmlbuilder/lib/XMLBuilder'` however I'm not sure I understand what caused it? 

Was this a regression introduced by #5179?

Also it seems like the validation step `continuous-integration/travis-ci/pr` is failing with the same error

**Comment by qiaozha** [comment]
> @qiaozha I'm not familiar with this package, can you please provide some details on what is the bug that this PR is fixing? I see that the error message is `Error: Cannot find module 'xmlbuilder/lib/XMLBuilder'` however I'm not sure I understand what caused it?
> 
> Was this a regression introduced by #5179?
> 
> Also it seems like the validation step `continuous-integration/travis-ci/pr` is failing with the same error

Yes this is a regression introduced by #5179 and the validation step is failing because it's trying to load the latest published azure-common instead of build from the PR's code in the serviceBus dependency. And since I haven't released this fix, the validation step is still using the problematic one. Seems like there's a paradox. 
I have tried to change the serviceBus dependency into my local built azure-common in package.json.
image
 It can pass the test.

**Comment by ramya-rao-a** [comment]
@qiaozha,

Can we consider reverting the changes from #5179, release an update to unblock the customer and then update this PR to do the fix the right way?

**Comment by ramya-rao-a** [comment]
That should help with the CI as well.

**Comment by qiaozha** [comment]
But the msportal is reporting another security bug of the old change

**Comment by ramya-rao-a** [comment]
I am only suggesting the revert temporarily until you figure out exactly what is causing the problem and answer questions that @joheredi has raised.

Teams using msportalfix would at max get the security vulnerability warning for another day or two
But in its current state, azure-common is breaking existing customers

**Comment by qiaozha** [comment]
> I am only suggesting the revert temporarily until you figure out exactly what is causing the problem and answer questions that @joheredi has raised.
> 
> Teams using msportalfix would at max get the security vulnerability warning for another day or two
> But in its current state, azure-common is breaking existing customers

okay, revert the change and re-released https://www.npmjs.com/package/azure-common/v/0.9.24 

The problem is caused by this file https://github.com/Azure/azure-sdk-for-node/pull/5182/files#diff-aae09a2931ddbc9cea60eedb94487627L19 and here https://github.com/Azure/azure-sdk-for-node/pull/5182/files#diff-345af09bd267b08e4253ea69f3330697L21 it has required this file but never used it. So I removed them in this PR.

**Comment by ramya-rao-a** [comment]
> it has required this file but never used it. So I removed them in this PR.

One need not directly use this file for it to be useful.

The file patches the `assertLegalChar()` method in the xml builder.
So, any code in this repo that uses this method or uses some other method in xml builder which then uses this method would have difference in behavior when we remove this patch.

**Comment by qiaozha** [comment]
I also searched assertLegalChar() it was not being used. Just found the CI is still failing not sure why and I can't repro in my local env

**Comment by ramya-rao-a** [comment]
> I also searched assertLegalChar() it was not being used

There is still a possibility that methods from xml builder that we do use may be using assertLegalChar()

**Comment by qiaozha** [comment]
In the 15.1.1 the only place that is using assertLegalChar is in ./node_modules/xmlbuilder/lib/XMLStringifier.js here 
image
But that one has its own definition 
image

**Comment by qiaozha** [comment]
Now all the CI tasks pass.

**Comment by joheredi** [comment]
> In the 15.1.1 the only place that is using assertLegalChar is in ./node_modules/xmlbuilder/lib/XMLStringifier.js here
> image
> But that one has its own definition
> image

@qiaozha as I understand it, the patched `assertLegalChar` removed in this PR was overriding the implementation you pointed out above, so when `xmlbuilder/lib/XMLStringifier.js` uses `assertLegalChar`, it is actually using the patched implementation. Removing the patched implementation would, as @ramya-rao-a mentioned, result in different behavior because now the original `assertLegalChar` function would be used.

I worry about removing the patch as it may cause unexpected behavior for consumers of this library.

The error `Error: Cannot find module 'xmlbuilder/lib/XMLBuilder'` seems to be caused by a refactor of the library. In the new version the function seems to be defined in `xmlbuilder/lib/XMLStringifier`

I think there are 2 ways we can proceed

1) Remove the patch - For this we need to be sure that the current implementation of `assertLegalChar` in XmlBuilder works for us and that the reason the patch was added in the first place has been fixed in XmlBuilder.

2) Update the patched `assertLegalChar` to work with the new XmlBuilder - This will keep the current behavior, a couple changes will be needed (1) replace `'xmlbuilder/lib/XMLBuilder'`  -> `'xmlbuilder/lib/XML'` and return `str` in the patched `assertLegalChar`

I think (2) would be less risky. What do you think?

**Comment by qiaozha** [comment]
@joheredi I do think (2) is a better way. and changed it back.

**Comment by qiaozha** [comment]
I should allso release a new package for legacyStorage as I have changed its way of xmlbuilder.create.

**Comment by joheredi** [comment]
Thanks @qiaozha, I used the following code to repro the issue and try out the changes in the patched function. It may be a good idea to add something similar to the unit tests to make sure we are covered in this front. I'm okay if this test is added in a follow up PR, your call.

```javascript
const common = require("./lib/common");

var x = common.js2xml.createElement("TestElement");

var y = common.js2xml.serializeDocument(x);

console.log(y);

```

**Comment by qiaozha** [comment]
> Thanks @qiaozha, I used the following code to repro the issue and try out the changes in the patched function. It may be a good idea to add something similar to the unit tests to make sure we are covered in this front. I'm okay if this test is added in a follow up PR, your call.
> 
> ```js
> const common = require("./lib/common");
> 
> var x = common.js2xml.createElement("TestElement");
> 
> var y = common.js2xml.serializeDocument(x);
> 
> console.log(y);
> ```

Thanks for point it out, I absolutely can add this.

**Comment by qiaozha** [comment]
> > Thanks @qiaozha, I used the following code to repro the issue and try out the changes in the patched function. It may be a good idea to add something similar to the unit tests to make sure we are covered in this front. I'm okay if this test is added in a follow up PR, your call.
> > ```js
> > const common = require("./lib/common");
> > 
> > var x = common.js2xml.createElement("TestElement");
> > 
> > var y = common.js2xml.serializeDocument(x);
> > 
> > console.log(y);
> > ```
> 
> Thanks for point it out, I absolutely can add this.
Just found there's already test here https://github.com/Azure/azure-sdk-for-node/blob/master/test/util/js2xml-tests.js#L145-L177 so I am going to merge and release the new package next week.
